"""Provided grid-MDP host for Midterm practice. DO NOT EDIT THIS FILE.

The autograder always uses the course copy of this file, so local edits
will not follow your submission. Your code goes in passive_rl.py and q_learning.py.

The MDP (fixed by the handout and quiz 1; the autograder pins it):
  states   free cells (row, col) of a coarse occupancy grid laid over a
           course map. Row 0 is the TOP of the map (maximum world y),
           col 0 the left, matching the Midterm practice grid convention.
  actions  0=N, 1=S, 2=E, 3=W (this order is pinned; greedy ties break
           toward the lower action index). N moves one row up (toward
           larger world y), E one column right (larger world x).
  moves    deterministic. Bumping a wall or the grid edge is a
           self-transition: the state does not change.
  reward   0 on every step, +GOAL_REWARD (=10) on ENTERING the goal
           cell. The goal is absorbing and terminal: the episode ends,
           and V(goal) = 0 by convention.
  discount GAMMA = 0.9.

The coarse grid: each MDP cell covers CELL_SIZE_M x CELL_SIZE_M meters
(1.0 m = 20 map pixels). A cell is free when the car's footprint
(CarParams().radius) fits at the cell center; this is the same collision
convention the simulator uses, so the MDP, PS1's A*, and PS1's RRT
all answer the same A-to-B question.
"""
import os

import numpy as np

from coursesim import CarParams, Map

import constants

# Action offsets in (drow, dcol), indexed 0..3 = N, S, E, W. Pinned.
ACTIONS = ((-1, 0), (1, 0), (0, 1), (0, -1))
ACTION_NAMES = ("N", "S", "E", "W")

_REPO_ROOT = os.path.dirname(os.path.dirname(
    os.path.dirname(os.path.abspath(__file__))))


def map_path(name):
    """Absolute path of a course map yaml under sim/maps/."""
    return os.path.join(_REPO_ROOT, "sim", "maps", name + ".yaml")


class GridMDP:
    """The Midterm practice grid MDP over an occupancy grid.

    Attributes (read-only by convention):
      occupancy  (H, W) bool array, True = wall.
      shape      (H, W).
      start      (row, col) start cell.
      goal       (row, col) goal cell, absorbing and terminal.
      actions    the pinned ACTIONS tuple.
      cell_size  meters per cell (for plots and the Midterm practice handoff).
      origin     world (x, y) of the grid's lower-left corner, meters.
    """

    def __init__(self, occupancy, start, goal, cell_size=1.0,
                 origin=(0.0, 0.0)):
        self.occupancy = np.asarray(occupancy, dtype=bool)
        self.shape = self.occupancy.shape
        self.start = tuple(int(v) for v in start)
        self.goal = tuple(int(v) for v in goal)
        self.actions = ACTIONS
        self.cell_size = float(cell_size)
        self.origin = (float(origin[0]), float(origin[1]))
        for name, cell in (("start", self.start), ("goal", self.goal)):
            if self.occupancy[cell]:
                raise ValueError(f"{name} cell {cell} is a wall")

    @classmethod
    def from_map(cls, name_or_path, cell_size=constants.CELL_SIZE_M):
        """Build the MDP for a course map ('open', 'maze', 'narrow').

        A coarse cell is free when Map.is_free holds at its center with
        the car's footprint radius. Start and goal are the cells
        containing the map's start and goal poses.
        """
        path = name_or_path if os.path.exists(str(name_or_path)) \
            else map_path(name_or_path)
        m = Map.load(path)
        radius = CarParams().radius
        h_px, w_px = m.occupancy.shape
        n_rows = int(h_px * m.resolution // cell_size)
        n_cols = int(w_px * m.resolution // cell_size)
        occ = np.ones((n_rows, n_cols), dtype=bool)
        for row in range(n_rows):
            for col in range(n_cols):
                x = m.origin[0] + (col + 0.5) * cell_size
                y = m.origin[1] + (n_rows - row - 0.5) * cell_size
                occ[row, col] = not m.is_free(x, y, radius=radius)

        def cell_of(pose):
            col = int((pose[0] - m.origin[0]) // cell_size)
            row = n_rows - 1 - int((pose[1] - m.origin[1]) // cell_size)
            return (row, col)

        return cls(occ, cell_of(m.start), cell_of(m.goal), cell_size,
                   (m.origin[0], m.origin[1]))

    # ------------------------------------------------------------ dynamics

    def step(self, s, a):
        """One MDP transition. s: (row, col) free cell. a: action index
        0..3 (N, S, E, W). Returns (s2, reward, done): s2 the next cell
        (== s on a bump), reward 0.0 or +10.0 on entering the goal, done
        True exactly when s2 is the goal. Deterministic, no RNG."""
        drow, dcol = ACTIONS[a]
        s2 = (s[0] + drow, s[1] + dcol)
        if not (0 <= s2[0] < self.shape[0] and 0 <= s2[1] < self.shape[1]) \
                or self.occupancy[s2]:
            s2 = s
        done = s2 == self.goal
        return s2, (constants.GOAL_REWARD if done else 0.0), done

    # ------------------------------------------------------------- helpers

    def free_cells(self):
        """List of all free (row, col) cells, row-major order."""
        return [tuple(c) for c in np.argwhere(~self.occupancy)]

    def cell_center_world(self, row, col):
        """World (x, y) meters of a cell center (plots, Midterm practice handoff)."""
        x = self.origin[0] + (col + 0.5) * self.cell_size
        y = self.origin[1] + (self.shape[0] - row - 0.5) * self.cell_size
        return x, y


class Stats:
    """Training counters for q_learning. Create one per training run,
    call record(s) once per environment step (with the state you acted
    FROM) and end_episode(reached_goal) when each episode ends.

    Fields:
      episodes        episodes finished
      successes       episodes that entered the goal
      updates         total Q-updates (== recorded steps)
      states_visited  number of unique states acted from
      episode_steps   list, steps taken in each episode
    """

    def __init__(self):
        self.episodes = 0
        self.successes = 0
        self.updates = 0
        self.episode_steps = []
        self._visited = set()
        self._steps_this_episode = 0

    def record(self, s):
        self._visited.add(tuple(s))
        self.updates += 1
        self._steps_this_episode += 1

    def end_episode(self, reached_goal):
        self.episodes += 1
        self.successes += int(bool(reached_goal))
        self.episode_steps.append(self._steps_this_episode)
        self._steps_this_episode = 0

    @property
    def states_visited(self):
        return len(self._visited)

    @property
    def mean_episode_steps(self):
        if not self.episode_steps:
            return float("nan")
        return float(np.mean(self.episode_steps))


def greedy_rollout(world, table, max_steps=200):
    """Roll the greedy policy out from world.start.

    table: either an (H, W) int array of action indices (a policy from
    extract_policy) or an (H, W, 4) Q table (greedy = argmax over the
    last axis, ties to the lower action index).

    Returns the number of steps taken to enter the goal, or None if the
    rollout bumps in place or exceeds max_steps without reaching it.
    """
    table = np.asarray(table)
    s = world.start
    for k in range(1, max_steps + 1):
        a = int(np.argmax(table[s])) if table.ndim == 3 else int(table[s])
        s2, _, done = world.step(s, a)
        if s2 == s:
            return None            # bumping in place: policy is stuck
        s = s2
        if done:
            return k
    return None
